export const articlesForSummary = [
  {
    relevance: 3,
    reason:
      "The article title suggests it discusses the development of an electric vehicle, but does not specify focus on batteries.",
    article_id: "f4879d4b4349705306d8ef55adfffc2b",
    title:
      "Apple aims for more realistic EV with fewer features to launch in 2028",
    link: "https://www.teslarati.com/apple-ev-fewer-features-2028/",
    keywords: ["news", "apple", "apple car", "featured", "project titan"],
    creator: ["Joey Klender"],
    video_url: null,
    description:
      "Apple is aiming to release its electric vehicle in 2028 and plans to equip the car with “limited autonomous driving,” a new report from Bloomberg states. After hoping to develop a driverless electric vehicle several years ago, Apple is scaling back its expectations for its introductory EV. The report states that Apple wants to develop its […] The post Apple aims for more realistic EV with fewer features to launch in 2028 appeared first on TESLARATI.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-01-23 20:54:57",
    image_url:
      "https://www.teslarati.com/wp-content/uploads/2020/12/tesla-tsla-rival-apple-car-vs-legacy-auto.jpg",
    source_id: "teslarati",
    source_url: "https://www.teslarati.com",
    source_priority: 19755,
    country: [
      "saudi arabia",
      "india",
      "united states of america",
      "canada",
      "singapore",
      "australia",
      "united kingdom"
    ],
    category: ["science", "technology"],
    language: "english",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS"
  },
  {
    relevance: 3,
    reason:
      "The article title suggests it discusses the development of an electric vehicle, but does not specify focus on batteries.",
    article_id: "a986e1c897f144afa698a9f85f3135f0",
    title:
      "Apple aims for more realistic EV with fewer features to launch in 2028",
    link: "https://zephyrnet.com/apple-aims-for-more-realistic-ev-with-fewer-features-to-launch-in-2028/",
    keywords: [
      "automotive",
      "featured",
      "2015",
      "2024",
      "2028",
      "23",
      "a",
      "abandon",
      "ability",
      "able",
      "acceleration",
      "adaptive",
      "after",
      "aiming",
      "aims",
      "air",
      "also",
      "altogether",
      "ambitious",
      "and",
      "and the",
      "any",
      "apple",
      "apple car",
      "archer",
      "archer aviation",
      "as",
      "at",
      "attempts",
      "autonomous",
      "autonomous driving",
      "autonomy",
      "aviation",
      "back",
      "be",
      "being",
      "bloomberg",
      "board",
      "board of directors",
      "bring",
      "but",
      "by",
      "can",
      "car",
      "centering",
      "ceo",
      "chips",
      "com",
      "comment",
      "comments",
      "companies",
      "company",
      "company's",
      "concerns",
      "concrete",
      "conservative",
      "constant",
      "control",
      "cook",
      "cool",
      "covered",
      "cruise",
      "cruise control",
      "d",
      "date",
      "deliver",
      "develop",
      "development",
      "directly",
      "director",
      "directors",
      "dr",
      "drive",
      "driver",
      "driverless",
      "driving",
      "electric",
      "electric vehicle",
      "email",
      "engineer",
      "engineering",
      "entirely",
      "equip",
      "ev",
      "eventually",
      "every",
      "expectations",
      "features",
      "few",
      "fewer",
      "find",
      "for",
      "forward",
      "four",
      "from",
      "full",
      "give",
      "give up",
      "had",
      "have",
      "hear",
      "high",
      "high-profile",
      "hit",
      "hoping",
      "however",
      "i",
      "if",
      "in",
      "initial",
      "initially",
      "introductory",
      "is",
      "it",
      "its",
      "january",
      "joey",
      "lane",
      "latest",
      "launch",
      "launched",
      "leaves",
      "left",
      "level",
      "like",
      "likely",
      "limited",
      "love",
      "make",
      "market",
      "me",
      "michael",
      "moment",
      "more",
      "new",
      "new car",
      "news",
      "notes",
      "of",
      "off",
      "on",
      "or",
      "over",
      "past",
      "pivotal",
      "plan",
      "planned",
      "plans",
      "plato",
      "plato data intelligence",
      "platodata",
      "please",
      "posted",
      "profile",
      "project",
      "provide",
      "questions",
      "reach",
      "realistic",
      "reasonable",
      "recruits",
      "regarding",
      "release",
      "report",
      "requires",
      "roughly",
      "s",
      "sae level 2",
      "scaling",
      "sees",
      "self",
      "self-driving",
      "senior",
      "several",
      "similar",
      "some",
      "some time",
      "spent",
      "staff",
      "started",
      "startup",
      "states",
      "steering",
      "still",
      "supervision",
      "support",
      "system",
      "table",
      "take",
      "taxi",
      "tesla",
      "tesla engineer",
      "tesla full self-driving",
      "teslarati",
      "that",
      "the",
      "things",
      "tim",
      "tim cook",
      "time",
      "tips",
      "to",
      "too",
      "toyota",
      "tsmc",
      "turnover",
      "twitter",
      "up",
      "us",
      "ve",
      "vehicle",
      "wants",
      "we",
      "well",
      "were",
      "what",
      "which?",
      "who",
      "will",
      "with",
      "work",
      "would",
      "years",
      "years ago",
      "you",
      "zephyrnet"
    ],
    creator: ["Republished By Plato"],
    video_url: null,
    description:
      "By Joey Klender Posted on January 23, 2024 Apple is aiming to release its electric vehicle in 2028 and plans to equip the car with “limited autonomous driving,” a new report from Bloomberg states. After hoping to develop a driverless electric vehicle several years ago, Apple is scaling back its expectations for its introductory EV. The […]",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-01-23 20:54:57",
    image_url:
      "https://zephyrnet.com/wp-content/uploads/2024/01/apple-aims-for-more-realistic-ev-with-fewer-features-to-launch-in-2028.jpg",
    source_id: "zephyrnet",
    source_url: "https://zephyrnet.com",
    source_priority: 3670004,
    country: ["united states of america"],
    category: ["technology"],
    language: "english",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS"
  }
];
export const articles = [
  {
    article_id: "d2d2278ab4029688d1405129470cb6dc",
    title: "Kelly Armstrong running for North Dakota governor",
    link: "https://www.inforum.com/news/north-dakota/kelly-armstrong-running-for-north-dakota-governor",
    keywords: null,
    creator: ["Patrick Springer"],
    video_url: null,
    description:
      "Armstrong, a three-term congressman, became the first to officially enter what could develop into a competitive GOP endorsement contest for governor.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-01-23 21:00:00",
    image_url:
      "https://cdn.forumcomm.com/dims4/default/3ef6327/2147483647/strip/true/crop/5961x3974+0+0/resize/840x560!/quality/90/?url=https%3A%2F%2Fforum-communications-production-web.s3.us-west-2.amazonaws.com%2Fbrightspot%2F1d%2F1c%2F4274750048099a2a3bfe8a2cda01%2Fndgop-convention-2022-1025.jpg",
    source_id: "inforum",
    source_url: "https://www.inforum.com",
    source_priority: 14163,
    country: ["united states of america"],
    category: ["top"],
    language: "english",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS"
  },

  {
    article_id: "f4879d4b4349705306d8ef55adfffc2b",
    title:
      "Apple aims for more realistic EV with fewer features to launch in 2028",
    link: "https://www.teslarati.com/apple-ev-fewer-features-2028/",
    keywords: ["news", "apple", "apple car", "featured", "project titan"],
    creator: ["Joey Klender"],
    video_url: null,
    description:
      "Apple is aiming to release its electric vehicle in 2028 and plans to equip the car with “limited autonomous driving,” a new report from Bloomberg states. After hoping to develop a driverless electric vehicle several years ago, Apple is scaling back its expectations for its introductory EV. The report states that Apple wants to develop its […] The post Apple aims for more realistic EV with fewer features to launch in 2028 appeared first on TESLARATI.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-01-23 20:54:57",
    image_url:
      "https://www.teslarati.com/wp-content/uploads/2020/12/tesla-tsla-rival-apple-car-vs-legacy-auto.jpg",
    source_id: "teslarati",
    source_url: "https://www.teslarati.com",
    source_priority: 19755,
    country: [
      "saudi arabia",
      "india",
      "united states of america",
      "canada",
      "singapore",
      "australia",
      "united kingdom"
    ],
    category: ["science", "technology"],
    language: "english",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS"
  },
  {
    article_id: "cce203076f34fb538429a2fd7f674ef1",
    title: "Take Your Portfolio to the Next Level with NIO Stock",
    link: "https://investorplace.com/2024/01/take-your-portfolio-to-the-next-level-with-nio-stock/",
    keywords: ["stocks to buy", "nyse:nio", "stocks to buy"],
    creator: ["Chris MacDonald"],
    video_url: null,
    description:
      "InvestorPlace - Stock Market News, Stock Advice & Trading Tips Here's why EV investors may want to consider NIO stock as a potential top option in 2024, for those looking at this space from a global lens. The post Take Your Portfolio to the Next Level with NIO Stock appeared first on InvestorPlace.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-01-23 20:50:06",
    image_url:
      "https://investorplace.com/wp-content/uploads/2023/10/nio1600-6-768x432.png",
    source_id: "investorplace",
    source_url: "https://investorplace.com",
    source_priority: 3707,
    country: ["united states of america"],
    category: ["top"],
    language: "english",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS"
  },
  {
    article_id: "bcad384e57dd55b26270decbea8387e9",
    title:
      "Apple Car Launch Date Reportedly Pushed Back To 2028—What We Know About The Electric Vehicle Project",
    link: "https://www.forbes.com/sites/antoniopequenoiv/2024/01/23/apple-car-launch-date-reportedly-pushed-back-to-2028-what-we-know-about-the-electric-vehicle-project/",
    keywords: [
      "business",
      "/business",
      "business",
      "/business",
      "breaking",
      "breaking-news",
      "topline"
    ],
    creator: [
      "Antonio Pequeño IV, Forbes Staff",
      "",
      "Antonio Pequeño IV, Forbes Staff",
      "",
      ""
    ],
    video_url: null,
    description:
      "The secretive car project, codenamed Titan, has been in development as far back as 2014, according to Bloomberg.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-01-23 20:40:22",
    image_url:
      "https://imageio.forbes.com/specials-images/imageserve/65b023f81c5c21355a1ff6db/0x0.jpg?width=960&precrop=4200%2C2362%2Cx0%2Cy217",
    source_id: "forbes",
    source_url: "https://www.forbes.com",
    source_priority: 57,
    country: ["united states of america"],
    category: ["business"],
    language: "english",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS"
  },
  {
    article_id: "c8aafe6c973c858e68b22fabd4009230",
    title:
      "The Apple car apparently still exists, could debut in 2028 with reduced autonomy",
    link: "https://www.engadget.com/the-apple-car-apparently-still-exists-could-debut-in-2028-with-reduced-autonomy-203458008.html?src=rss",
    keywords: [
      "site|engadget",
      "provider_name|engadget",
      "region|us",
      "language|en-us",
      "author_name|will shanklin"
    ],
    creator: ["Will Shanklin"],
    video_url: null,
    description:
      "Apple has reportedly scaled back its automotive aspirations, at least for now. Bloomberg’s Mark Gurman says the company’s decade-old vehicle project has pivoted from planning a fully self-driving car to an EV more like Tesla’s. The so-called “Apple Car” is now projected to launch no earlier than 2028 — two years after the company’s last reported target date. The car’s autonomous features have reportedly been downgraded from a Level 5 system (full automation) to a Level 4 system (full automation in some circumstances) — and now to a Level 2+ one (partial automation). That would mean it offers limited self-driving features like lane centering and braking / accelerating support — while still requiring the driver’s full attention. Tesla’s Autopilot is categorized as Level 2. Level 2+ isn’t an official designation, but it’s sometimes used informally to describe a more advanced version of Level 2. What Apple once envisioned as a car without a steering wheel or pedals — and perhaps having a remote command center ready to take over for a driver — now looks more like a Tesla-like market entrance. Tesla’s Model 3Photo by Roberto Baldwin / Engadget Bloomberg says Apple views the project’s downscaling internally as “a pivotal moment.” People familiar with Apple’s plans allegedly believe delivering the pared-down Apple Car with reduced expectations could make or break the entire project. “Either the company is finally able to deliver this product with reduced expectations or top executives may seriously reconsider the project’s existence,” Gurman wrote. Apple has reportedly talked with potential manufacturing partners in Europe about the updated strategy. Bloomberg says the company still wants to offer a Level 4 autonomous system at some point, even as its debut is on track for something more grounded. Bloomberg describes the meetings leading up to Apple’s decision as “frenzied,” involving CEO Tim Cook, the Apple board and project head Kevin Lynch. The latter took over after former leader Doug Field left in 2021. (Field was a former Tesla engineering head who now leads Ford’s EV wing.) The board reportedly pushed leadership about the car plan throughout 2023. After starting well out of the blocks, self-driving cars didn’t have a great 2023. Cruise, GM’s robotaxi division, laid off 24 percent of its workforce in December. That came after one of the company’s vehicles pinned and dragged a pedestrian who had been hit by another car. The aftermath was swift, as the California DMV suspended Cruise’s driverless permits over safety concerns. On the brighter side, Waymo seems to be doing well. But government standards are the wild card in this equation, and perhaps Apple saw the wind blowing in a direction that warranted caution. Apple’s Project Titan has been the subject of rumors since at least the mid-2010s. The company has spent hundreds of millions of dollars on the initiative. It’s worked on “powertrains, self-driving hardware and software, car interiors and exteriors, and other key components,” according to Gurman. Given how many times the expensive project’s details have changed, don’t be surprised if they do so again.This article originally appeared on Engadget at https://www.engadget.com/the-apple-car-apparently-still-exists-could-debut-in-2028-with-reduced-autonomy-203458008.html?src=rss",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-01-23 20:34:58",
    image_url:
      "https://o.aolcdn.com/images/dims?image_uri=https%3A%2F%2Fs.yimg.com%2Fos%2Fcreatr-uploaded-images%2F2024-01%2F3dd7d8a0-ba2b-11ee-be2f-6eb43959be6a&resize=1400%2C787&client=19f2b5e49a271b2bde77&signature=106e38666b96dcee7e2e24ada6d6b23829eb3316",
    source_id: "engadget",
    source_url: "https://www.engadget.com",
    source_priority: 2082,
    country: [
      "india",
      "united kingdom",
      "singapore",
      "united states of america"
    ],
    category: ["technology"],
    language: "english",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS"
  },
  {
    article_id: "9f408a273e6d135141d7d7920c9a5216",
    title:
      "Durham K-9, handler honored for tracking down armed suspect hiding in trash can",
    link: "https://www.cbs17.com/news/local-news/durham-county-news/durham-k-9-handler-honored-for-tracking-down-armed-suspect-hiding-in-trash-can/",
    keywords: [
      "durham county news",
      "crime tracker",
      "local news",
      "news",
      "the bright side ☀️"
    ],
    creator: ["Ashley Anderson"],
    video_url: null,
    description:
      "After police said a man fired a gun at a vehicle with two women inside, a Durham K-9 and his handler are being honored for bringing a foot chase to an end.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-01-23 20:33:59",
    image_url:
      "https://www.cbs17.com/wp-content/uploads/sites/29/2024/01/F-55.png?w=900",
    source_id: "cbs17",
    source_url: "https://www.cbs17.com",
    source_priority: 12160,
    country: ["united states of america"],
    category: ["top"],
    language: "english",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS"
  },
  {
    article_id: "4b7d4f60252958c28940a681f0629a45",
    title: "4 Tips to Avoid EV Battery Issues in Cold Weather - CNET",
    link: "https://www.cnet.com/roadshow/news/4-tips-to-avoid-ev-battery-issues-in-cold-weather/#ftag=CAD5457c2c",
    keywords: null,
    creator: ["Sam Becker"],
    video_url: null,
    description:
      "Recent reports of stranded Tesla drivers in snowy Chicago shows us that owning an EV comes with its disadvantages. But experts say there are ways to prepare for extreme cold (and hot) weather before you drive.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-01-23 20:30:03",
    image_url:
      "https://www.cnet.com/a/img/resize/fdbac55cc0ca6a3cd71e9e4492dffba02a3f7ca2/hub/2024/01/23/be7e1c21-47e4-40da-85ba-36f963c42fa5/gettyimages-1940909807.jpg?auto=webp&width=300",
    source_id: "cnet",
    source_url: "https://www.cnet.com",
    source_priority: 155,
    country: ["united states of america"],
    category: ["top"],
    language: "english",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS"
  },
  {
    article_id: "09923e393c519c964a8d723391ed705a",
    title: "4 Tips to Avoid EV Battery Issues in Cold Weather - CNET",
    link: "https://www.cnet.com/roadshow/news/4-tips-to-avoid-ev-battery-issues-in-cold-weather/#ftag=CADf328eec",
    keywords: null,
    creator: ["Sam Becker"],
    video_url: null,
    description:
      "Recent reports of stranded Tesla drivers in snowy Chicago shows us that owning an EV comes with its disadvantages. But experts say there are ways to prepare for extreme cold (and hot) weather before you drive.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-01-23 20:30:03",
    image_url:
      "https://www.cnet.com/a/img/resize/fdbac55cc0ca6a3cd71e9e4492dffba02a3f7ca2/hub/2024/01/23/be7e1c21-47e4-40da-85ba-36f963c42fa5/gettyimages-1940909807.jpg?auto=webp&width=300",
    source_id: "cnet",
    source_url: "https://www.cnet.com",
    source_priority: 155,
    country: ["united states of america"],
    category: ["top"],
    language: "english",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS"
  },
  {
    article_id: "6d8c53d1ee632f325d6f56789ab958db",
    title: "4 Tips to Avoid EV Battery Issues in Cold Weather",
    link: "https://www.cnet.com/roadshow/news/4-tips-to-avoid-ev-battery-issues-in-cold-weather/#ftag=CAD7f780fb",
    keywords: null,
    creator: ["Sam Becker"],
    video_url: null,
    description:
      "Recent reports of stranded Tesla drivers in snowy Chicago shows us that owning an EV comes with its disadvantages. But experts say there are ways to prepare for extreme cold (and hot) weather before you drive.",
    content: "ONLY AVAILABLE IN PAID PLANS",
    pubDate: "2024-01-23 20:30:03",
    image_url:
      "https://www.cnet.com/a/img/resize/fdbac55cc0ca6a3cd71e9e4492dffba02a3f7ca2/hub/2024/01/23/be7e1c21-47e4-40da-85ba-36f963c42fa5/gettyimages-1940909807.jpg?auto=webp&width=300",
    source_id: "cnet",
    source_url: "https://www.cnet.com",
    source_priority: 155,
    country: ["united states of america"],
    category: ["top"],
    language: "english",
    ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
    ai_region: "ONLY AVAILABLE IN CORPORATE PLANS"
  }
];
export const articlesShort = [
  {
    title: "Kelly Armstrong running for North Dakota governor",
    article_id: "d2d2278ab4029688d1405129470cb6dc"
  },
  {
    title:
      "Apple aims for more realistic EV with fewer features to launch in 2028",
    article_id: "a986e1c897f144afa698a9f85f3135f0"
  },
  {
    title:
      "Apple aims for more realistic EV with fewer features to launch in 2028",
    article_id: "f4879d4b4349705306d8ef55adfffc2b"
  },
  {
    title: "Take Your Portfolio to the Next Level with NIO Stock",
    article_id: "cce203076f34fb538429a2fd7f674ef1"
  },
  {
    title:
      "Apple Car Launch Date Reportedly Pushed Back To 2028—What We Know About The Electric Vehicle Project",
    article_id: "bcad384e57dd55b26270decbea8387e9"
  },
  {
    title:
      "The Apple car apparently still exists, could debut in 2028 with reduced autonomy",
    article_id: "c8aafe6c973c858e68b22fabd4009230"
  },
  {
    title:
      "Durham K-9, handler honored for tracking down armed suspect hiding in trash can",
    article_id: "9f408a273e6d135141d7d7920c9a5216"
  },
  {
    title: "4 Tips to Avoid EV Battery Issues in Cold Weather - CNET",
    article_id: "4b7d4f60252958c28940a681f0629a45"
  },
  {
    title: "4 Tips to Avoid EV Battery Issues in Cold Weather - CNET",
    article_id: "09923e393c519c964a8d723391ed705a"
  },
  {
    title: "4 Tips to Avoid EV Battery Issues in Cold Weather",
    article_id: "6d8c53d1ee632f325d6f56789ab958db"
  }
];

export const interest = "EV batteries";
